version: '3.5'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        working_dir: /app
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ../:/app
        ports:
            - '80:80'
        depends_on:
            - php
            - mysql
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        container_name: php
        restart: always
        volumes:
            - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "../:/var/www/html"
    composer:
        image: "composer"
        container_name: composer
        volumes:
            - "../:/app"
        command: install
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./mysql:/var/lib/mysql"
